trigger: none

parameters:
  - name: TestPackagesEnabled 
    type: object
    default:
      - identity
      - chat
      - phonenumbers
      - sms
      - mgmt

stages:
  - ${{ each package in parameters.TestPackagesEnabled }}:
    - template: ../../eng/pipelines/templates/stages/archetype-sdk-tests.yml
      parameters:
        CloudConfig:
          Public:
            SubscriptionConfiguration: $(sub-config-communication-services-cloud-test-resources)
          Int:
            SubscriptionConfiguration: $(sub-config-communication-int-test-resources)
        Clouds: Public,Int
        AllocateResourceGroup: 'false'
        ${{ if ne(package, 'mgmt') }}:
          BuildTargetingString: ${{ format('azure-communication-{0}', package) }}
        ${{ if eq(package, 'mgmt') }}:
          BuildTargetingString: 'azure-mgmt-communication'
        JobName: ${{ package }}
        ServiceDirectory: communication
        DeployArmTemplate: true
        EnvVars:
          AZURE_TEST_RUN_LIVE: 'true'
          AZURE_SUBSCRIPTION_ID: $(acs-subscription-id)
          AZURE_COMMUNICATION_SERVICE_PHONE_NUMBER: $(communication-livetest-phone-number)
