# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._request_builders_py3 import build_set_properties_request
    from ._request_builders_py3 import build_get_properties_request
    from ._request_builders_py3 import build_get_statistics_request
    from ._request_builders_py3 import build_list_containers_segment_request
    from ._request_builders_py3 import build_get_user_delegation_key_request
    from ._request_builders_py3 import build_get_account_info_request
    from ._request_builders_py3 import build_submit_batch_request
    from ._request_builders_py3 import build_filter_blobs_request
except (SyntaxError, ImportError):
    from ._request_builders import build_set_properties_request  # type: ignore
    from ._request_builders import build_get_properties_request  # type: ignore
    from ._request_builders import build_get_statistics_request  # type: ignore
    from ._request_builders import build_list_containers_segment_request  # type: ignore
    from ._request_builders import build_get_user_delegation_key_request  # type: ignore
    from ._request_builders import build_get_account_info_request  # type: ignore
    from ._request_builders import build_submit_batch_request  # type: ignore
    from ._request_builders import build_filter_blobs_request  # type: ignore

__all__ = [
    'build_set_properties_request',
    'build_get_properties_request',
    'build_get_statistics_request',
    'build_list_containers_segment_request',
    'build_get_user_delegation_key_request',
    'build_get_account_info_request',
    'build_submit_batch_request',
    'build_filter_blobs_request',
]
