# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._request_builders_py3 import build_download_request
    from ._request_builders_py3 import build_get_properties_request
    from ._request_builders_py3 import build_delete_request
    from ._request_builders_py3 import build_set_access_control_request
    from ._request_builders_py3 import build_get_access_control_request
    from ._request_builders_py3 import build_rename_request
    from ._request_builders_py3 import build_undelete_request
    from ._request_builders_py3 import build_set_expiry_request
    from ._request_builders_py3 import build_set_http_headers_request
    from ._request_builders_py3 import build_set_metadata_request
    from ._request_builders_py3 import build_acquire_lease_request
    from ._request_builders_py3 import build_release_lease_request
    from ._request_builders_py3 import build_renew_lease_request
    from ._request_builders_py3 import build_change_lease_request
    from ._request_builders_py3 import build_break_lease_request
    from ._request_builders_py3 import build_create_snapshot_request
    from ._request_builders_py3 import build_start_copy_from_url_request
    from ._request_builders_py3 import build_copy_from_url_request
    from ._request_builders_py3 import build_abort_copy_from_url_request
    from ._request_builders_py3 import build_set_tier_request
    from ._request_builders_py3 import build_get_account_info_request
    from ._request_builders_py3 import build_query_request
    from ._request_builders_py3 import build_get_tags_request
    from ._request_builders_py3 import build_set_tags_request
except (SyntaxError, ImportError):
    from ._request_builders import build_download_request  # type: ignore
    from ._request_builders import build_get_properties_request  # type: ignore
    from ._request_builders import build_delete_request  # type: ignore
    from ._request_builders import build_set_access_control_request  # type: ignore
    from ._request_builders import build_get_access_control_request  # type: ignore
    from ._request_builders import build_rename_request  # type: ignore
    from ._request_builders import build_undelete_request  # type: ignore
    from ._request_builders import build_set_expiry_request  # type: ignore
    from ._request_builders import build_set_http_headers_request  # type: ignore
    from ._request_builders import build_set_metadata_request  # type: ignore
    from ._request_builders import build_acquire_lease_request  # type: ignore
    from ._request_builders import build_release_lease_request  # type: ignore
    from ._request_builders import build_renew_lease_request  # type: ignore
    from ._request_builders import build_change_lease_request  # type: ignore
    from ._request_builders import build_break_lease_request  # type: ignore
    from ._request_builders import build_create_snapshot_request  # type: ignore
    from ._request_builders import build_start_copy_from_url_request  # type: ignore
    from ._request_builders import build_copy_from_url_request  # type: ignore
    from ._request_builders import build_abort_copy_from_url_request  # type: ignore
    from ._request_builders import build_set_tier_request  # type: ignore
    from ._request_builders import build_get_account_info_request  # type: ignore
    from ._request_builders import build_query_request  # type: ignore
    from ._request_builders import build_get_tags_request  # type: ignore
    from ._request_builders import build_set_tags_request  # type: ignore

__all__ = [
    'build_download_request',
    'build_get_properties_request',
    'build_delete_request',
    'build_set_access_control_request',
    'build_get_access_control_request',
    'build_rename_request',
    'build_undelete_request',
    'build_set_expiry_request',
    'build_set_http_headers_request',
    'build_set_metadata_request',
    'build_acquire_lease_request',
    'build_release_lease_request',
    'build_renew_lease_request',
    'build_change_lease_request',
    'build_break_lease_request',
    'build_create_snapshot_request',
    'build_start_copy_from_url_request',
    'build_copy_from_url_request',
    'build_abort_copy_from_url_request',
    'build_set_tier_request',
    'build_get_account_info_request',
    'build_query_request',
    'build_get_tags_request',
    'build_set_tags_request',
]
