# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._request_builders_py3 import build_upload_request
    from ._request_builders_py3 import build_put_blob_from_url_request
    from ._request_builders_py3 import build_stage_block_request
    from ._request_builders_py3 import build_stage_block_from_url_request
    from ._request_builders_py3 import build_commit_block_list_request
    from ._request_builders_py3 import build_get_block_list_request
except (SyntaxError, ImportError):
    from ._request_builders import build_upload_request  # type: ignore
    from ._request_builders import build_put_blob_from_url_request  # type: ignore
    from ._request_builders import build_stage_block_request  # type: ignore
    from ._request_builders import build_stage_block_from_url_request  # type: ignore
    from ._request_builders import build_commit_block_list_request  # type: ignore
    from ._request_builders import build_get_block_list_request  # type: ignore

__all__ = [
    'build_upload_request',
    'build_put_blob_from_url_request',
    'build_stage_block_request',
    'build_stage_block_from_url_request',
    'build_commit_block_list_request',
    'build_get_block_list_request',
]
