# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._request_builders_py3 import build_create_request
    from ._request_builders_py3 import build_get_properties_request
    from ._request_builders_py3 import build_delete_request
    from ._request_builders_py3 import build_set_metadata_request
    from ._request_builders_py3 import build_get_access_policy_request
    from ._request_builders_py3 import build_set_access_policy_request
    from ._request_builders_py3 import build_restore_request
    from ._request_builders_py3 import build_rename_request
    from ._request_builders_py3 import build_submit_batch_request
    from ._request_builders_py3 import build_acquire_lease_request
    from ._request_builders_py3 import build_release_lease_request
    from ._request_builders_py3 import build_renew_lease_request
    from ._request_builders_py3 import build_break_lease_request
    from ._request_builders_py3 import build_change_lease_request
    from ._request_builders_py3 import build_list_blob_flat_segment_request
    from ._request_builders_py3 import build_list_blob_hierarchy_segment_request
    from ._request_builders_py3 import build_get_account_info_request
except (SyntaxError, ImportError):
    from ._request_builders import build_create_request  # type: ignore
    from ._request_builders import build_get_properties_request  # type: ignore
    from ._request_builders import build_delete_request  # type: ignore
    from ._request_builders import build_set_metadata_request  # type: ignore
    from ._request_builders import build_get_access_policy_request  # type: ignore
    from ._request_builders import build_set_access_policy_request  # type: ignore
    from ._request_builders import build_restore_request  # type: ignore
    from ._request_builders import build_rename_request  # type: ignore
    from ._request_builders import build_submit_batch_request  # type: ignore
    from ._request_builders import build_acquire_lease_request  # type: ignore
    from ._request_builders import build_release_lease_request  # type: ignore
    from ._request_builders import build_renew_lease_request  # type: ignore
    from ._request_builders import build_break_lease_request  # type: ignore
    from ._request_builders import build_change_lease_request  # type: ignore
    from ._request_builders import build_list_blob_flat_segment_request  # type: ignore
    from ._request_builders import build_list_blob_hierarchy_segment_request  # type: ignore
    from ._request_builders import build_get_account_info_request  # type: ignore

__all__ = [
    'build_create_request',
    'build_get_properties_request',
    'build_delete_request',
    'build_set_metadata_request',
    'build_get_access_policy_request',
    'build_set_access_policy_request',
    'build_restore_request',
    'build_rename_request',
    'build_submit_batch_request',
    'build_acquire_lease_request',
    'build_release_lease_request',
    'build_renew_lease_request',
    'build_break_lease_request',
    'build_change_lease_request',
    'build_list_blob_flat_segment_request',
    'build_list_blob_hierarchy_segment_request',
    'build_get_account_info_request',
]
