# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._request_builders_py3 import build_create_request
    from ._request_builders_py3 import build_upload_pages_request
    from ._request_builders_py3 import build_clear_pages_request
    from ._request_builders_py3 import build_upload_pages_from_url_request
    from ._request_builders_py3 import build_get_page_ranges_request
    from ._request_builders_py3 import build_get_page_ranges_diff_request
    from ._request_builders_py3 import build_resize_request
    from ._request_builders_py3 import build_update_sequence_number_request
    from ._request_builders_py3 import build_copy_incremental_request
except (SyntaxError, ImportError):
    from ._request_builders import build_create_request  # type: ignore
    from ._request_builders import build_upload_pages_request  # type: ignore
    from ._request_builders import build_clear_pages_request  # type: ignore
    from ._request_builders import build_upload_pages_from_url_request  # type: ignore
    from ._request_builders import build_get_page_ranges_request  # type: ignore
    from ._request_builders import build_get_page_ranges_diff_request  # type: ignore
    from ._request_builders import build_resize_request  # type: ignore
    from ._request_builders import build_update_sequence_number_request  # type: ignore
    from ._request_builders import build_copy_incremental_request  # type: ignore

__all__ = [
    'build_create_request',
    'build_upload_pages_request',
    'build_clear_pages_request',
    'build_upload_pages_from_url_request',
    'build_get_page_ranges_request',
    'build_get_page_ranges_diff_request',
    'build_resize_request',
    'build_update_sequence_number_request',
    'build_copy_incremental_request',
]
